"$schema" = "https://cdn.posit.co/publisher/schemas/posit-publishing-schema-v3.json"
type = "html"
entrypoint = "_site/index.html"
title = "WAV Monitoring Summaries"
source = "index.qmd"
files = [
    "/_site",
    "/.posit/publish/Water Action Volunteers-EMDR.toml",
    "/.posit/publish/deployments/deployment-7EFK.toml",
]
validate = true
product_type = "connect"
